### ISSUE TITLE
LSM6DSOX with Nucleo-F401RE

### ISSUE THREAD

**Issue by musmanabid** [stm32duino/X-NUCLEO-IKS01A3#13]
I am currently using the following setup:

[NUCLEO-F401RE]
[X-NUCLEO-IKS01A2]
[STEVAL-MKI197V1]

I want to be able to use the ARDUINO IDE to LOAD configuration files (.ucf files) to the LSM6DSOX and use the Machine Learning Core(MLC) feature.

I have tried looking at the Arduino Library code for the [LSM6DSOX](https://github.com/stm32duino/LSM6DSOX). Whenever I run this code, in the output, I get the repeated values, it doesn't change the value

Can anyone provide a high-level Arduino code that is able to upload the configuration file to the MLC and is able to read out the MLC registers, Interrupts and accelerometer values ?

**Comment by cparata** [comment]
Hello @musmanabid ,
did you try [this example](https://github.com/stm32duino/X-NUCLEO-IKS01A3/blob/main/examples/X_NUCLEO_IKS01A3_LSM6DSOX_MLC/X_NUCLEO_IKS01A3_LSM6DSOX_MLC.ino)? It should work as it is also with X-NUCLEO-IKS01A2. Please, pay attention to connect correctly the STEVAL-MKI197V1 to the X-NUCLEO-IKS01A2. The pin 1 of STEVAL-MKI197V1 (the only one squared) must be connected to the pin 1 of the DIL24 connector (the one indicated with a point on the PCB).
Best Regards,
Carlo

**Comment by musmanabid** [comment]
Hello @cparata 
Thanks for the help. I tried this example, it worked fine for me. Thanks a lot for your help.

Kind Regards
Usman
