### ISSUE TITLE
error: 'float_t' does not name a type

### ISSUE THREAD

**Issue by swortain** [stm32duino/X-NUCLEO-IKS01A3#4]
I install the library (and all the dependence)in Arduino IDE, But I got some ERROR while compile the example program like this
![image](https://user-images.githubusercontent.com/6780386/61522603-40e92f80-aa45-11e9-85fd-3b3a3160b474.png)

**Comment by swortain** [comment]
BTW I compile for Arduino UNO which is not stm32duino but arduino...

**Comment by cparata** [comment]
Hi @swortain ,
thanks to have notified this issue. I fixed it in the new release of LSM6DSO (v1.0.2).
Best Regards,
Carlo
