### ISSUE TITLE
Example on how to upload configuration to MLC

### ISSUE THREAD

**Issue by jatincc** [stm32duino/X-NUCLEO-IKS01A3#7]
I am currently using the following setup:

[NUCLEO-L476RG](https://www.st.com/en/evaluation-tools/nucleo-l476rg.html)
[X-NUCLEO-IKS01A3](https://www.st.com/en/ecosystems/x-nucleo-iks01a3.html)
[STEVAL-MKI197V1](https://www.st.com/en/evaluation-tools/steval-mki197v1.html)

I want to be able to use the ARDUINO IDE to LOAD configuration files (.ucf files) to the LSM6DSOX and use the Machine Learning Core(MLC) feature.

I have tried looking at the Arduino Library code for the [LSM6DSOX](https://github.com/stm32duino/LSM6DSOX) and the [X-NUCLEO-IKS01A3](https://github.com/stm32duino/X-NUCLEO-IKS01A3).
But there are no examples on how to do this.

Can anyone provide a high-level Arduino code that is able to upload configuration file to the MLC and is able to read out the MLC registers and Interrupts?

Edit:
UNICO generates a .h file using the .ucf file.
So arduino code would be using that header file NOT the .ucf file directly.
Like this: [LINK](https://github.com/STMicroelectronics/STMems_Machine_Learning_Core/tree/master/lsm6dsox/Activity%20recognition%20for%20mobile)

I have also put this issue on the [LSM6DSOX](https://github.com/stm32duino/LSM6DSOX) Github page as I am not really sure where it belongs.

**Comment by cparata** [comment]
Hi @khepri420 ,
I will try to prepare an example in 2 days and I will come back to you.
Best Regards,
Carlo

**Comment by cparata** [comment]
Hi @khepri420 ,
I updated the LSM6DSOX library and the X-NUCLEO-IKS01A3 library adding an example with MLC using the STEVAL-MKI197V1. You can download the new versions from the master repositories. It implements the activity recognition MLC that you linked in the previous post. Let me know if it works on your side. Unfortunately I do not have one STEVAL-MKI197V1 to test it by myself. If it works on your side I will release a new version of LSM6DSOX and X-NUCLEO-IKS01A3 libraries with this new feature.
Best Regards,
Carlo

**Comment by jatincc** [comment]
Hey @cparata ,
Thanks for a quick response.
I have tried the example but I am getting "Unknown" value from the switch case in the setup().
And not getting any interrupts at all after that.
I think it may be due to different jumper configuration on my end.
Can you specify what jumper configuration you have?

**Comment by cparata** [comment]
Hi @khepri420 ,
strange, the only thing is to have SB46 closed. I will try to get a STEVAL-MKI197V1 and I will give a try to the code.
Best Regards,
Carlo

**Comment by cparata** [comment]
Hi @khepri420 ,
finally I got one STEVAL-MKI197V1 and I was able to figure out the issue. Basically when we use the LSM6DSOX with the DIL24 adapter of X-NUCLEO-IKS01A3 (but it is the same also with X-NUCLEO-IKS01A2), the LSM6DSOX starts in I3C mode because there is a level shifter on X-NUCLEO-IKS01A3 that keeps the INT1 of LSM6DSOX high and so the component starts in I3C mode as specified in the Datasheet. The best solution that I found, it was to patch the sketch and the MLC bytecode in order to route the MLC event on INT2 instead of INT1. In order to get the sketch working, you need to put A5 pin to GND with a wire, so LSM6DSOX can start in I2C mode and set JP6 to close pins 13 and 14 instead of 5 and 6 in order to have the M_INT2_O on pin D2. I hope now that it works also on your side.
Best Regards,
Carlo

**Comment by jatincc** [comment]
Hi @cparata ,
Thanks for the fix. It is working now.
I will do some additional testing and come back to close this issue in a couple of days.
Thanks for you help.

**Comment by cparata** [comment]
Hi @khepri420 ,
it seems that it also possible to have a software patch on the I3C issue. So I rewrite a bit the code reusing INT1 of LSM6DSOX and avoiding the usage of the wire. Could you tell me if it works on your side, because I cannot test it.
Thanks in advance.
Best Regards,
Carlo

**Comment by jatincc** [comment]
It did indeed work. 
But needs one minor fix.

Following should be **d**igitalWrite()

https://github.com/stm32duino/X-NUCLEO-IKS01A3/blob/2ad3d531f8ecfc07a793c62991070563c6eab8c5/examples/X_NUCLEO_IKS01A3_LSM6DSOX_MLC/X_NUCLEO_IKS01A3_LSM6DSOX_MLC.ino#L81

**Comment by cparata** [comment]
Hi @khepri420 ,
thanks! I also reworked a bit the MLC sketch in order to remove redundant pieces of code. If you agree, I would close the ticket and release the new version of the LSM6DSOX and X-NUCLEO-IKS01A3 libraries.
Best Regards,
Carlo
